package models

import (
	"errors"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"golang.org/x/crypto/bcrypt"

	"gitlab.com/go-courses/lenslocked.com/hash"
	"gitlab.com/go-courses/lenslocked.com/rand"
)

var (
	// ErrNotFound is returned when a record cannot be found
	ErrNotFound  = errors.New("models: resource not found")

	// ErrInvalidID is returned when an ID is 0, for example
	ErrInvalidID = errors.New("models: ID provided was invalid")

	// ErrInvalidPassword is returned when an invalid password is used
	// when authenticating a user
	ErrInvalidPassword = errors.New("models: incorrect password provided")
)

const userPwPepper = "some-secret"
const hmacSecretKey = "secret-hmac-key"

// UserDB interface is used for interacting with the users database.
//
// For prettry much all single user queries:
// If the user is found, we will return a nil error
// If the user is not found, we will return a ErrNotFound
// If there is another error, we will return an error with
// additional information about what went wrong. This may not be an error
// generated by the model package.
//
// For single user queries, any error but ErrNotFound should
// probably result in a 500 error.
type UserDB interface {
	// Methods for querying for single users
	ByID(id uint) (*User, error)
	ByEmail(id string) (*User, error)
	ByRemember(toke string) (*User, error)

	// Methods for altering users
	Create(user *User) error
	Update(user *User) error
	Delete(id uint) error

	// Used to close a DB Connection
	Close() error

	// Migration Helpers
	AutoMigrate() error
	DestructiveReset() error
}


type User struct {
	gorm.Model
	Name         string
	Email        string `gorm:"not null;unique_index"`
	Password     string `gorm:"-"`
	PasswordHash string `gorm:"not null"`
	Remember      string `gorm:"-"`
	RememberHash string `gorm:"not null;unique_index"`
}

func NewUserService(connectionInfo string) (*UserService, error) {
  ug, err := newUserGorm(connectionInfo)
	if err != nil {
		return nil, err
		}
	return &UserService{
		UserDB: &userValidator{
			UserDB: ug,
		},
	}, nil
}

type UserService struct {
  UserDB
}

type userValidator struct {
	UserDB
}

type userGorm struct {
	db   *gorm.DB
	hmac hash.HMAC
}

func newUserGorm(connectionInfo string) (*userGorm, error) {
	db, err := gorm.Open("postgres", connectionInfo)
	if err != nil {
		return nil, err
	}
	db.LogMode(true)
	hmac := hash.NewHMAC(hmacSecretKey)
	return &userGorm{
		db:   db,
		hmac: hmac,
	}, nil
}


// Compiler check that type matches interface
var _ UserDB = &userGorm{}

// ByID method allows us to find a user
func (ug *userGorm) ByID(id uint) (*User, error) {
	var user User
	db := ug.db.Where("id = ?", id)
	err := first(db, &user)
	return &user, err
}

// Lookup a user by Email in the database
func (ug *userGorm) ByEmail(email string) (*User, error) {
	var user User
	db := ug.db.Where("email = ?", email)
	err := first(db, &user)
	return &user, err
}

// Lookup by Remember looks up user by Remeber token
// this method wil handle hasing the token for us
func (ug *userGorm) ByRemember(token string) (*User, error) {
	var user User
	rememberHash := ug.hmac.Hash(token)
	db := ug.db.Where("remember_hash = ?", rememberHash)
	err := first(db, &user)
	if err != nil {
		return nil, err
	}
	return &user, err
}

// Lookup a users by Age Range in the database
func (ug *userGorm) InAgeRange(minAge, maxAge uint) ([]User, error) {
	var users []User
	db := ug.db.Where("age BETWEEN ? and ?", minAge, maxAge)
	err := find(db, &users)
	return users, err
}


// first is a help function for Lookups and it will get the first item
// returned and place into destination.
// orig: func first(db *gorm.DB, user *User) error {
func first(db *gorm.DB, destination interface{}) error {
	err := db.First(destination).Error
	if err == gorm.ErrRecordNotFound {
	  return ErrNotFound
	}
	return err
}

// find is a help function for Lookups and it will get the first item
// returned and place into destination.
// orig: func first(db *gorm.DB, user *User) error {
func find(db *gorm.DB, destination interface{}) error {
	err := db.Find(destination).Error
	if err == gorm.ErrRecordNotFound {
	  return ErrNotFound
	}
	return err
}

//Creates a user in the database and will backfill
// related meta-data like ID, CreatedAt...
func (ug *userGorm) Create(user *User) error {
	pwBytes :=[]byte(user.Password + userPwPepper)
	hashedBytes, err := bcrypt.GenerateFromPassword(pwBytes, bcrypt.DefaultCost)
	if err != nil {
		return err
	}
	user.PasswordHash = string(hashedBytes)
	user.Password = ""

	if user.Remember == "" {
		token, err := rand.RememberToken()
		if err != nil {
			return err
		}
		user.Remember = token
	}
	user.RememberHash = ug.hmac.Hash(user.Remember)
	return ug.db.Create(user).Error
}


// Authenticates a user login request
// takes an email and Password
// If the email doesn't exist
//   return nil and ErrNotFound
// If the password provided doesn't match the hased password
//   return nil and an ErrInvalidPassword
// If the email and password are both valid
//   return the user and nil
// Otherwise another system error was encountered
//   return nil and the error
func (us *UserService) Authenticate(email, password string) (*User, error) {
	foundUser, err := us.ByEmail(email)
	if err != nil {
		return nil, err
	}

	err =bcrypt.CompareHashAndPassword([]byte(foundUser.PasswordHash), []byte(password + userPwPepper))
	if err != nil {
		switch err {
		case bcrypt.ErrMismatchedHashAndPassword:
			return nil, ErrInvalidPassword
		default:
			return nil, err
		}
	}
	 return foundUser, nil

}

// Update a user in the database
func (ug *userGorm) Update(user *User) error {
	if user.Remember != "" {
		user.RememberHash = ug.hmac.Hash(user.Remember)
	}
	return ug.db.Save(user).Error
}

// Delete a user in the database
func (ug *userGorm) Delete(id uint) error {
	if id == 0 {
		return ErrInvalidID
	}
	user := User{Model: gorm.Model{ID: id}}
	return ug.db.Delete(&user).Error
}

// Closes the UserService database connection
func (ug *userGorm) Close() error {
	return ug.db.Close()
}

// DestructiveReset drops the user table and rebuilds it
func (ug *userGorm) DestructiveReset() error {
	if err := ug.db.DropTableIfExists(&User{}).Error; err != nil {
		return err
	}
	return ug.AutoMigrate()
}

// Automigrate will attempt to automatically migrate the users table
func (ug *userGorm) AutoMigrate() error {
	if err := ug.db.AutoMigrate(&User{}).Error; err != nil {
		return err
	}
	return nil

}
